d={
    'I':'I',
    'II':'II',
    'III':'III',
    'IV':'IV',
    'V':'V',
    'VI':'IV',
    'VII':'VII',
    'VIII':'VIII',
    'IX':'IX',
    'X':'X',
    'XI':'IX',
    'XII':'XII',
    'XIII':'XIII',
    'XIV':'XIV',
    'XV':'XV',
    'XVI':'XIV',
    'XVII':'XVII',
    'XVIII':'XVIII',
    'XIX':'XIX',
    'XX':'XX',
    'XXI':'XIX',
    'XXII': 'XXII',
    'XXIII': 'XXIII',
    'XXIV': 'XXIV',
    'XXV': 'XXV',
    'XXVI': 'XXIV',
    'XXVII': 'XXVII',
    'XXVIII': 'XXVIII',
    'XXIX': 'XXIX',
    'XXX': 'XXX',
    'XXXI': 'XXIX',
    'XXXII': 'XXXII',
    'XXXIII': 'XXXIII',
    'XXXIV': 'XXXIV',
    'XXXV': 'XXXV',
    'XXXVI': 'XXXIV',
    'XXXVII': 'XXXVII',
    'XXXVIII': 'XXXVIII',
    'XXXIX': 'XXXIX',
    'XL': 'XL',
    'XLI': 'XLI',
    'XLII': 'XLII',
    'XLIII': 'XLIII',
    'XLIV': 'XLIV',
    'XLV': 'XLV',
    'XLVI': 'XLIV',
    'XLVII': 'XLVII',
    'XLVIII': 'XLVIII',
    'XLIX': 'XLIX',
    'L': 'L',
    'LI': 'LI',
    'LII': 'LII',
    'LIII': 'LIII',
    'LIV': 'LIV',
    'LV': 'LV',
    'LVI': 'LIV',
    'LVII': 'LVII',
    'LVIII': 'LVIII',
    'LIX': 'LIX',
    'LX': 'XL',
    'LXI': 'XLI',
    'LXII': 'XLII',
    'LXIII': 'XLIII',
    'LXIV': 'XLIV',
    'LXV': 'XLV',
    'LXVI': 'XLIV',
    'LXVII': 'XLVII',
    'LXVIII': 'XLVIII',
    'LXIX': 'XLIX',
    'LXX': 'LXX',
    'LXXI': 'XLIX',
    'LXXII': 'LXXII',
    'LXXIII': 'LXXIII',
    'LXXIV': 'LXXIV',
    'LXXV': 'LXXV',
    'LXXVI': 'LXXIV',
    'LXXVII': 'LXXVII',
    'LXXVIII': 'LXXVIII',
    'LXXIX': 'LXXIX',
    'LXXX': 'LXXX',
    'LXXXI': 'LXXIX',
    'LXXXII': 'LXXXII',
    'LXXXIII': 'LXXXIII',
    'LXXXIV': 'LXXXIV',
    'LXXXV': 'LXXXV',
    'LXXXVI': 'LXXXIV',
    'LXXXVII': 'LXXXVII',
    'LXXXVIII': 'LXXXVIII',
    'LXXXIX': 'LXXXIX',
    'XC': 'XC',
    'XCI': 'XCI',
    'XCII': 'XCII',
    'XCIII': 'XCIII',
    'XCIV': 'XCIV',
    'XCV': 'XCV',
    'XCVI': 'XCIV',
    'XCVII': 'XCVII',
    'XCVIII': 'XCVIII',
    'XCIX': 'XCIX'
}
print(d[input()])